mixed-port: 10808
authentication:
  - "vvip1:vvip1"
ipv6: false
mode: rule
log-level: info
allow-lan: false
external-controller: 127.0.0.1:9090
unified-delay: true
dns:
  enable: true
  enabled: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - tls://dns.google:853
  fallback:
    - tls://dns.rubyfish.id:853
    - tls://1.0.0.1:853

proxies:
  - {'name': 'SG-BYU_SS_pvwtr-SG1_GlobalSSH', 'type': 'ss', 'server': 'space.byu.id', 'port': 443, 'password': 'GlobalSSHPremiumShadow==:H4gwwpXniwrMPdhX19rXDw==', 'cipher': '2022-blake3-aes-128-gcm', 'plugin': 'v2ray-plugin', 'plugin-opts': {'mode': 'websocket', 'tls': True, 'skip-cert-verify': True, 'host': 'ss-ovh-sg01.globalssh.xyz', 'path': '/shadow-ws', 'mux': False}}

proxy-groups:
  - name: TraficSG
    type: select
    strategy: round-robin
    disable-udp: false
    proxies:
      - SG-BYU_SS_pvwtr-SG1_GlobalSSH
      - Hijacking
    url: http://www.gstatic.com/generate_204
    interval: 360
  - name: Hijacking
    type: select
    disable-udp: true
    proxies:
      - REJECT
    url: http://www.gstatic.com/generate_204
    interval: 360

rule-providers:
  rule_block:
    type: file
    behavior: domain
    path: "./rule_block.yaml"

rules:
  - RULE-SET,rule_block,Hijacking,no-resolved
  - MATCH,TraficSG
